### ISSUE TITLE
recompile shader when source file changes

### ISSUE THREAD

**Issue by joobei** [bbar2/V4_Shaders#1]
I'm curious if your cmake shader compilation works even if the main target does not get built. i.e. I want to have a shader re-built whenever its source changes but that doesn't seem to happen unless the main target changes.

https://github.com/bbar2/V4_Shaders/blob/32085f12ed0692c292bca09df29254eaf4687bdd/CMakeLists.txt#L65

Would that work with your approach? if not, any ideas how to?

**Comment by joobei** [comment]
I ended up using add_custom_command in file generation mode, not as a pre or post build step to another target

**Comment by bbar2** [comment]
I see you are past this now.  It's been a while since I played with CMake and shaders.  As I recall, my approach compiled the shader, but only when the project source was updated.  CMake did not detect the shader update with my approach -- as you already observed.   

Did you add_custom_command approach achieve the desired result, of updating when there was a shader update only?

**Comment by joobei** [comment]
Yes. add_custom_command in file generation mode works, so long as the filename "generated" is in the file list of some target. If you are interested in accomplishing this I can share my cmakefile.

**Comment by bbar2** [comment]
Yes please share.  I'd like to see how you did that.

**Comment by joobei** [comment]
The only problem with this implementation is that the building/copying happens every single build. I haven't figured out how to make it happen ONLY when the shader source changes. I will post here if I sort that out.

```
#copy asset.gltf from source dir to where the target is being built
add_custom_command(
        OUTPUT asset.gltf
        COMMAND ${CMAKE_COMMAND} -E copy ${PROJECT_SOURCE_DIR}/asset.gltf $<TARGET_FILE_DIR:${CMAKE_PROJECT_NAME}>/
        DEPENDS ${PROJECT_SOURCE_DIR}/asset.gltf
        VERBATIM)

add_custom_target(assets DEPENDS asset.gltf)

#compile shaders and copy where the target is being built/shaders
function(compile_shader SHADER_NAME SHADER_TYPE)
    add_custom_command(
        OUTPUT ${SHADER_NAME}.spv
        COMMAND ${CMAKE_COMMAND} -E make_directory $<TARGET_FILE_DIR:${CMAKE_PROJECT_NAME}>/shaders
        COMMAND ${Vulkan_GLSLC_EXECUTABLE} -fshader-stage=${SHADER_TYPE} ${PROJECT_SOURCE_DIR}/shaders/${SHADER_NAME}.glsl -o $<TARGET_FILE_DIR:${CMAKE_PROJECT_NAME}>/shaders/${SHADER_NAME}.spv
        DEPENDS ${PROJECT_SOURCE_DIR}/shaders/${SHADER_NAME}.glsl
        VERBATIM)
endfunction()

compile_shader("vertex" "vert")
compile_shader("fragment" "frag")



add_executable (${PROJECT_NAME} Renderer.cpp vertex.spv fragment.spv)
add_dependencies(${PROJECT_NAME} assets)
```

**Comment by bbar2** [comment]
Thanks - we can't seem to find the perfect CMake solution for building shaders only when needed.  We either do it every time, or have to force a rebuild if the shader source is the only thing edited.  Either approach is really OK.  I'm sure CMake can do what we want, I just don't know how to coax CMake to do it.
